server:
  port: 8081
  servlet:
    context-path: /

cloudaa:
  kafka:
    consumer:
      bootstrap-servers-config: BROKER-VM1-IP,BROKER-VM2-IP,BROKER-VM3-IP
      key-deserializer-class-config: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer-class-config: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id-config: cloud-aa-1
